### ISSUE TITLE
Error alarm under managed cluster

### ISSUE THREAD

**Issue by luoyuctl** [kubesphere/notification-manager#115]
![image](https://user-images.githubusercontent.com/51604064/146338147-3f98dbaf-e400-459e-9640-e005de553a36.png)

environment:
Kubesphere:3.20
Kubernetes:1.20.4

Under a managed cluster, it is normal for K8s master components to be invisible and should not be an alert.

I hope to provide a way to manually turn off the built-in alarm policy in the system or other ways to block this kind of alarm.

**Comment by benjaminhuo** [comment]
Notification filter can be set to avoid sending specified alerts.
@wanjunlei can explain this for you

**Comment by wanjunlei** [comment]
You can filter the notification messages received by the global notification channel in KubeSphere 3.2.0 like this.

<img width="960" alt="1639705870(1)" src="https://user-images.githubusercontent.com/53003665/146475606-9918e38a-8f01-4715-a410-1d2fc81bdc79.png">


If you want to filter the notification messages received by the tenant notification channel, you can edit the crd to achieve it, you can refer to this.
https://github.com/kubesphere/notification-manager#notification-filter

**Comment by luoyuctl** [comment]
> You can filter the notification messages received by the global notification channel in KubeSphere 3.2.0 like this.
> 
> <img alt="1639705870(1)" width="960" src="https://user-images.githubusercontent.com/53003665/146475606-9918e38a-8f01-4715-a410-1d2fc81bdc79.png">
> 
> If you want to filter the notification messages received by the tenant notification channel, you can edit the crd to achieve it, you can refer to this. https://github.com/kubesphere/notification-manager#notification-filter

it can't works , when i save，the value missing

**Comment by wanjunlei** [comment]
Please click `Enter` after you set the label value.
