### ISSUE TITLE
a mistake of code

### ISSUE THREAD

**Issue by gliffcheung** [kubesphere/notification-manager#135]
@wanjunlei 
In this [line](https://github.com/kubesphere/notification-manager/blob/master/pkg/dispatcher/dispatcher.go#L109) of code, it may be like this:
```go
func (d *Dispatcher) releaseWorker() {
	<-d.semCh
}
```

**Comment by wanjunlei** [comment]
Thanks for your feedback, would you like to submit a PR to fix this bug?

**Comment by benjaminhuo** [comment]
Fixed by https://github.com/kubesphere/notification-manager/pull/136
