### ISSUE TITLE
if AWS is supported as the provider for SMS services

### ISSUE THREAD

**Issue by Bennu-Li** [kubesphere/notification-manager#140]
I saw in the notification-manager documentation that the provider supports huawei, aliyun, tencent when the receiver is SMS. I would like to know if AWS is currently supported as the provider for SMS services.

https://github.com/kubesphere/notification-manager/blob/master/docs/crds/receiver.md#sms-receiver

**Comment by wanjunlei** [comment]
Not yet supported.

**Comment by benjaminhuo** [comment]
@Bennu-Li You're welcome to create a PR to support AWS SMS

**Comment by Bennu-Li** [comment]
Hi, I'd love to create a pr to support AWS SMS. But I'm not familiar with the source code for this project, and I might need some help, as well as trying to understand the amount of work required to implement this feature.

**Comment by wanjunlei** [comment]
Thank you for supporting our community. I will briefly introduce how to support AWS SMS.

First, you need to modify the [Config CRD](https://github.com/kubesphere/notification-manager/blob/master/pkg/apis/v2beta2/config_types.go#L150), and add an SMS provider of AWS. At the same time, it is necessary to add the verification of the AWS provider like [this](https://github.com/kubesphere/notification-manager/blob/master/pkg/apis/v2beta2/config_webhook.go#L112). 

Second, modify the [internal SMS Config](https://github.com/kubesphere/notification-manager/blob/master/pkg/apis/v2beta2/config_webhook.go#L112).

Then, you can find the implementation of sending notifications to aliyun SMS [here](https://github.com/kubesphere/notification-manager/tree/master/pkg/notify/notifier/sms), you can follow this to implement sending notifications to AWS SMS.

**Comment by Bennu-Li** [comment]
> modify the [internal SMS Config](https://github.com/kubesphere/notification-manager/blob/master/pkg/apis/v2beta2/config_webhook.go#L112)
> verification of the AWS provider like [this](https://github.com/kubesphere/notification-manager/blob/master/pkg/apis/v2beta2/config_webhook.go#L112).

The description is very detailed and I already have a general understanding of how this feature is implemented.

But the link you provided for the verification of provider and the internal SMS Config are the same, I'm not sure that's it?

**Comment by wanjunlei** [comment]
> 

Yes, both places need to be modified.

**Comment by wanjunlei** [comment]
> > modify the [internal SMS Config](https://github.com/kubesphere/notification-manager/blob/master/pkg/apis/v2beta2/config_webhook.go#L112)
> > verification of the AWS provider like [this](https://github.com/kubesphere/notification-manager/blob/master/pkg/apis/v2beta2/config_webhook.go#L112).
> 
> The description is very detailed and I already have a general understanding of how this feature is implemented.
> 
> But the link you provided for the verification of provider and the internal SMS Config are the same, I'm not sure that's it?

Sorry, the second link is [this](https://github.com/kubesphere/notification-manager/blob/master/pkg/internal/sms/types.go#L119)

**Comment by Bennu-Li** [comment]
Okay, I'll start implementing this feature this week.

**Comment by Bennu-Li** [comment]
Hi, how should I quickly test the AWS Sms module I added. Is there an example of a relevant unit test, such as for Aliyun Sms?

**Comment by benjaminhuo** [comment]
@zhu733756 , how did you test SMS for tecent/aliyun/huawei before?

**Comment by zhu733756** [comment]
Add the related CRs, checking the message from SMS provider. You can also debug the process locally.

**Comment by Bennu-Li** [comment]
> debug the process locally.
How to debug it locally? Can you give me some details?

**Comment by benjaminhuo** [comment]
or use [nokohost](https://nocalhost.dev/) to debug k8s apps
