### ISSUE TITLE
sms receiver: 17212345678 is not a valid phone number

### ISSUE THREAD

**Issue by Bennu-Li** [kubesphere/notification-manager#155]
I use api `/api/v2/verify` to verify the SMS, but I always get the following error, no matter what`phoneNumbers` is.
```
{"Status":400,"Message":"sms receiver: 17212345678 is not a valid phone number"}

{"Status":400,"Message":"sms receiver: +8617212345678 is not a valid phone number"}
```

**Comment by wanjunlei** [comment]
This is a bug, the relevant code is [here](https://github.com/kubesphere/notification-manager/blob/82a83184c2565b36f05c1c0c252bf1aeebd289aa/pkg/internal/sms/types.go#L68).

Do you want to commit a pr to fix this bug?

**Comment by Bennu-Li** [comment]
> This is a bug, the relevant code is [here](https://github.com/kubesphere/notification-manager/blob/82a83184c2565b36f05c1c0c252bf1aeebd289aa/pkg/internal/sms/types.go#L68).
> 
> Do you want to commit a pr to fix this bug?

Okay, I'll do it.
