### ISSUE TITLE
Can notification-Manager（1.0.0） inKubespherev3.1.1 be upgraded to 2.0? 

### ISSUE THREAD

**Issue by cao99** [kubesphere/notification-manager#164]
Can notification-Manager（1.0.0） inKubespherev3.1.1 be upgraded to 2.0? 
How to upgrade?

**Comment by cao99** [comment]
我只需要和重新安装一样 apply 这三条命令么？旧版本会自动更新吧

**Comment by cao99** [comment]
whether   K8S 1.18 can install  kubesphere 3.2/3.3？

**Comment by wanjunlei** [comment]
> whether K8S 1.18 can install kubesphere 3.2/3.3？ In the document minimum version required is 1.19+

No, it needs K8s 1.19+.

https://kubesphere.io/zh/docs/v3.3/quick-start/minimal-kubesphere-on-k8s/#%E5%87%86%E5%A4%87%E5%B7%A5%E4%BD%9C

**Comment by wanjunlei** [comment]
> 

Yes

**Comment by cao99** [comment]
tks ！

**Comment by cao99** [comment]
after upgrade， here are many error logs notification-manager pod ：

========================================================================
level=info ts=2022-09-01T18:00:45.275793469+08:00 caller=config.go:583 msg="resource change" op=add name=default-wechat-config
level=error ts=2022-09-01T18:02:35.11345599+08:00 caller=webhook.go:45 msg="WebhookNotifier: get template error" error="template: template:1: function \"translate\" not defined"
level=error ts=2022-09-01T18:02:35.116810688+08:00 caller=dingtalk.go:84 msg="DingTalkNotifier: get template error" error="template: template:1: function \"translate\" not defined"
level=error ts=2022-09-01T18:02:35.119991301+08:00 caller=email.go:57 msg="EmailNotifier: get template error" error="template: template:1: function \"translate\" not defined"
level=error ts=2022-09-01T18:02:35.125467415+08:00 caller=wechat.go:75 msg="WechatNotifier: get template error" error="template: template:1: function \"translate\" not defined"
level=error ts=2022-09-01T18:02:35.128427322+08:00 caller=slack.go:53 msg="SlackNotifier: get template error" error="template: template:1: function \"translate\" not defined"
level=error ts=2022-09-01T18:34:50.341830247+08:00 caller=email.go:57 msg="EmailNotifier: get template error" error="template: template:1: function \"translate\" not defined"
level=error ts=2022-09-01T18:34:50.344442806+08:00 caller=wechat.go:75 msg="WechatNotifier: get template error" error="template: template:1: function \"translate\" not defined"
level=error ts=2022-09-01T18:34:50.347415554+08:00 caller=slack.go:53 msg="SlackNotifier: get template error" error="template: template:1: function \"translate\" not defined"
level=error ts=2022-09-01T18:34:50.350599069+08:00 caller=webhook.go:45 msg="WebhookNotifier: get template error" error="template: template:1: function \"translate\" not defined"
level=error ts=2022-09-01T18:34:50.353561262+08:00 caller=dingtalk.go:84 msg="DingTalkNotifier: get template error" error="template: template:1: function \"translate\" not defined"
level=error ts=2022-09-01T18:47:14.939000569+08:00 caller=slack.go:53 msg="SlackNotifier: get template error" error="template: template:1: function \"translate\" not defined"
level=error ts=2022-09-01T18:47:14.942229439+08:00 caller=webhook.go:45 msg="WebhookNotifier: get template error" error="template: template:1: function \"translate\" not defined"
level=error ts=2022-09-01T18:47:14.945540039+08:00 caller=dingtalk.go:84 msg="DingTalkNotifier: get template error" error="template: template:1: function \"translate\" not defined"
level=error ts=2022-09-01T18:47:14.948557429+08:00 caller=email.go:57 msg="EmailNotifier: get template error" error="template: template:1: function \"translate\" not defined"
level=error ts=2022-09-01T18:47:14.951879674+08:00 caller=wechat.go:75 msg="WechatNotifier: get template error" error="template: template:1: function \"translate\" not defined"
level=error ts=2022-09-01T19:37:38.01489954+08:00 caller=wechat.go:75 msg="WechatNotifier: get template error" error="template: template:1: function \"translate\" not defined"
level=error ts=2022-09-01T19:37:38.0189735+08:00 caller=slack.go:53 msg="SlackNotifier: get template error" error="template: template:1: function \"translate\" not defined"
level=error ts=2022-09-01T19:37:38.024468881+08:00 caller=webhook.go:45 msg="WebhookNotifier: get template error" error="template: template:1: function \"translate\" not defined"
level=error ts=2022-09-01T19:37:38.028760915+08:00 caller=dingtalk.go:84 msg="DingTalkNotifier: get template error" error="template: template:1: function \"translate\" not defined"
level=error ts=2022-09-01T19:37:38.031867104+08:00 caller=email.go:57 msg="EmailNotifier: get template error" error="template: template:1: function \"translate\" not defined"
level=error ts=2022-09-01T20:09:50.341756098+08:00 caller=email.go:57 msg="EmailNotifier: get template error" error="template: template:1: function \"translate\" not defined"
level=error ts=2022-09-01T20:09:50.345283506+08:00 caller=wechat.go:75 msg="WechatNotifier: get template error" error="template: template:1: function \"translate\" not defined"
level=error ts=2022-09-01T20:09:50.348089811+08:00 caller=slack.go:53 msg="SlackNotifier: get template error" error="template: template:1: function \"translate\" not defined"
level=error ts=2022-09-01T20:09:50.350488646+08:00 caller=webhook.go:45 msg="WebhookNotifier: get template error" error="template: template:1: function \"translate\" not defined"
level=error ts=2022-09-01T20:09:50.352898953+08:00 caller=dingtalk.go:84 msg="DingTalkNotifier: get template error" error="template: template:1: function \"translate\" not defined"

**Comment by wanjunlei** [comment]
kubectl edit nm notification-manager

change the image tag to v2.0.1

**Comment by wanjunlei** [comment]
No need to clean and reinstall, just create notificationmanager cr use following command

kubectl apply -f https://github.com/kubesphere/notification-manager/releases/download/v2.0.0/notification_manager.yaml

**Comment by cao99** [comment]
NM working now, Tks a lot.
