### ISSUE TITLE
whether we can define a global receiver to just send  warning notifications for a whole K8S cluster?

### ISSUE THREAD

**Issue by cao99** [kubesphere/notification-manager#166]
I have try below config, but still can receive many warning alerts.
![image](https://user-images.githubusercontent.com/39616902/191011024-f0fa32cf-56be-44d2-8cec-009b8c302f18.png)
![image](https://user-images.githubusercontent.com/39616902/191011399-fd84821c-d5d9-464f-b561-9082181433c1.png)
![image](https://user-images.githubusercontent.com/39616902/191011729-9cb7e814-c3cb-4990-b906-3d17cfde34cc.png)

**Comment by benjaminhuo** [comment]
@wanjunlei Any thoughts on this? As I can understand the router and alertselector in receiver is duplicated, we can keep one of them

**Comment by wanjunlei** [comment]
@cao99 check if there any other receivers send to the wechat user `CaoYY`.

And the `WeChat` in `Router` will be the low case, it should be `wechat`.

**Comment by cao99** [comment]
> @cao99 check if there any other receivers send to the wechat user `CaoYY`.
> 
> And the `WeChat` in `Router` will be the low case, it should be `wechat`.

Just one receiver to the wechat user `CaoYY`. 
I will try to change to the low case: wecat

**Comment by cao99** [comment]
I delete all routers, and just config alertSelector in the global receiver. Now can't receiver any new notifications even `warning` alerts. 
![image](https://user-images.githubusercontent.com/39616902/191161278-85233293-4dc7-4886-b7e5-d7124fe7590e.png)

**Comment by wanjunlei** [comment]
change the log level to debug, check if any alerts are received

https://github.com/kubesphere/notification-manager/blob/master/docs/crds/notification-manager.md#args

**Comment by cao99** [comment]
@wanjunlei  below are logs
![image](https://user-images.githubusercontent.com/39616902/191187151-f08cb379-581a-4f6a-8151-eedeb5d65dca.png)

**Comment by wanjunlei** [comment]
From the log, the alerts were filtered out in the filter stage, you can create a global receiver without alertSelector to check that alerts with the error or critical severity have been received.

**Comment by cao99** [comment]
If remove alertSelector from receiver,  we can receive  `warning` `error`  `critical` severity  alerts.

**Comment by wanjunlei** [comment]
a spelling error, the `serverity` should be `severity`.

**Comment by cao99** [comment]
Tks a lot, working now.  Copy  config from here,  the spelling error need to update also. 
https://github.com/kubesphere/notification-manager/blob/master/docs/crds/receiver.md
![image](https://user-images.githubusercontent.com/39616902/191245108-5ae869c6-0ce7-496c-bdaa-55707ebba4e2.png)
