### ISSUE TITLE
不支持企业微信机器人

### ISSUE THREAD

**Issue by chuchq** [kubesphere/notification-manager#168]
企业微信机器人是使用企业微信的企业最常用的一个工具，目前kubesphere中并不支持此功能，webhook也无法发送到企业微信机器人的webhook

**Comment by Shuimo03** [comment]
请问现在是否支持企业微信机器人？

**Comment by Shuimo03** [comment]
好的，十分感谢！

**Comment by zuoyangs** [comment]
> > 请问现在是否支持企业微信机器人？
> 
> https://github.com/kubesphere/notification-manager/blob/master/docs/crds/receiver.md#wechat-chatbot 已经支持了

这个不支持企业微信群的webhook吧？
