### ISSUE TITLE
Add support to send notifications to telegram 

### ISSUE THREAD

**Issue by wanjunlei** [kubesphere/notification-manager#170]

**Comment by arvingre** [comment]
Add support to send notifications to telegram That will  be nice one

**Comment by benjaminhuo** [comment]
@arvingre Just wondering if you have a time slot to work on this?
You can refer to the discord implementation https://github.com/kubesphere/notification-manager/pull/185

**Comment by mangoGoForward** [comment]
I'd like to work on this, please assign to me.
/assign

**Comment by benjaminhuo** [comment]
Great! Thanks @mangoGoForward
