### ISSUE TITLE
SMTP DDOS / Endless test alert

### ISSUE THREAD

**Issue by yngfoxx** [kubesphere/notification-manager#172]
![image](https://user-images.githubusercontent.com/47150226/203765959-67e64420-80fa-4983-a608-e786ba6778dc.png)

I just configured the alert system and it seemed to be okay, until It started sending emails endlessly, had to immediately disable alert.

I setup webhook and email

For the webhook I used this URL: 
```
http://notification-manager-svc.kubesphere-monitoring-system.svc:19093/api/v2/alerts
```

I was trying to workout the webhook so I can hook it up to a discord channel, so I am not really sure but I think it created an endless loop 🤷‍♂️

**Comment by yngfoxx** [comment]
![image](https://user-images.githubusercontent.com/47150226/203767924-6ed18d7f-401c-4f1b-b3f9-908b5db06f64.png)

All systems going down 😭

**Comment by benjaminhuo** [comment]
The endless alerts are caused by the system being down?
Not a notification manager issue?

**Comment by yngfoxx** [comment]
It is a domino effect, after the email ddos all systems started going down one by one

**Comment by yngfoxx** [comment]
The systems are now coming back up, let me get the logs I can find

**Comment by benjaminhuo** [comment]
You shouldn't config webhook receiver to `http://notification-manager-svc.kubesphere-monitoring-system.svc:19093/api/v2/alerts`

This address is the source of notification, not to receive notification, and should be configured as alertmanager webook, not in notification manager's webhook receiver

**Comment by yngfoxx** [comment]
> You shouldn't config webhook receiver to `http://notification-manager-svc.kubesphere-monitoring-system.svc:19093/api/v2/alerts`
> 
> This address is the source of notification, not to receive notification, and should be configured as alertmanager webook, not in notification manager's webhook receiver

That makes sense, I see that is my fault then I thought the Notification channel was were I put the alertmanager webhook
![image](https://user-images.githubusercontent.com/47150226/203772335-c3523faf-b094-4fa1-8511-575b92a492b1.png)
