### ISSUE TITLE
告警认领相关问题请教

### ISSUE THREAD

**Issue by Shuimo03** [kubesphere/notification-manager#200]
在notify阶段进行告警通知的时候，是否支持告警认领？或者在IM工具中艾特对应负责人？

**Comment by Gentleelephant** [comment]
@用户是可以的，例如企业微信机器人https://github.com/kubesphere/notification-manager/blob/master/docs/crds/receiver.md#WeChat-Receiver

**Comment by Shuimo03** [comment]
多谢
