### ISSUE TITLE
Logo for Notification Manager

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/notification-manager#93]
@wanjunlei @benjaminhuo @junotx @zhu733756 
Our designer has provided a new logo for Notification Manager, how do you think of it?

![image](https://user-images.githubusercontent.com/40452856/127614884-d5f6da6a-390b-4155-a271-6238a25f252f.png)

**Comment by benjaminhuo** [comment]
Fantastic！Looks perfect

**Comment by benjaminhuo** [comment]
Does it make more sense to make the ring red as Prometheus logo to indicate it's an alert and it's from Prometheus https://avatars.githubusercontent.com/u/3380462?s=200&v=4 @FeynmanZhou
